VB-TB-S-10 Stage-10
drop189/VocabularyBuilderTelegramBot pull request #10
Opened 2024-06-04 20:00 UTC by drop189

2024-06-06 23:26 UTC, danelyan commented on build.gradle.kts
> +    kotlin("jvm") version "2.0.0"
о, второй котлин ) новье 👍🏻

2024-06-06 23:27 UTC, danelyan commented on readme.md
> +Бот для изучения английских слов.
Отлично 🔥 И старайся всегда делать небольшую доку в репозиториях, даже если это небольшой скрипт – ты будущий скажешь себе спасибо )

2024-06-06 23:37 UTC, danelyan requested changes
Давай добавим кнопку для выхода из процесса изучения слов.
Добавочной кнопкой внизу:

<img width="370" alt="Screenshot 2024-06-07 at 02 34 32" src="https://github.com/drop189/VocabularyBuilderTelegramBot/assets/7125622/154eca01-92fd-4ad5-88b6-d872ea9dfaa7">

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val response: Response = json.decodeFromString(responseString)
Давай немного оптимизируем. Если посмотреть внимательнее, мы можем убрать json внутрь telegramBotService. И сделать так, чтобы метод getUpdates() возвращал сразу `Response`

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    json: Json,
тогда этот параметр json можно убрать

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    if (text.equals("Hello", ignoreCase = true)) telegramBotService.sendMessage(
Hello нам уже не нужен. Если хочешь, можно как пасхалку оставить )

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    if (text.equals("/start", ignoreCase = true)) telegramBotService.sendMenu(json, chatId)
Эти два if можно объединить, они делают одно и то же. Например при помощи `or`.
И кстати, если json будет внутри telegramBotService, его не надо будет прокидывать в метод `sendMenu()`

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
>          val client: HttpClient = HttpClient.newBuilder().build()
HttpClient можно вынести в поле класса TelegramBotService(), чтобы не создавать при каждом вызове метода. Его достаточно создать один раз вместе с TelegramBotService()

2024-06-06 23:37 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +            replyMarkup = ReplyMarkup(question?.variants!!.mapIndexed { index, word ->
Старайся избегать использования !!.

А давай подумаем, почему у нас variants может быть нулябельным?
Потому что question передается нулябельным. А можно сделать его не нулябельным?
Да, ведь при нулевом question весь метод не имеет смысла, что означает "отправить нулевой вопрос"? (вопрос риторический).

Давай уберем нулябельность и сопутствующие операторы, а проверку на нуль делегируем коду выше (который вызывает `sendQuestion()`)

2024-06-08 18:31 UTC, danelyan requested changes
На мой взгляд - теперь все идеально )

Но, как ты мог заметить, есть проблема со стабильностью – приложение периодически прекращает свою работу. При этом в логах мы видим ошибку при обращении к API Telegram'а.

На самом деле сетевые запросы могут фейлится по разным причинам:
- отсутствие сети на виртуалке
- временно недоступен сервер Telegram
- слишком много запросов (иногда сервер может заподозрить DDOS и начать отвечать с ошибкой)
- и другие проблемы.

Поэтому нам следует защитить подобные места. Ведь по сути, если запрос закончился с ошибкой, нам просто можно повторить его через пару секунд, а не ронять приложение.

Давай в тех частях кода где используется `send(...)` отлавливать сетевые ошибки. Можно использовать `try ... catch` или `runCatching {}`

2024-06-08 18:33 UTC, danelyan commented
> ... в тех частях кода 

в твоем случае - в одном месте :D

2024-06-10 16:17 UTC, drop189 commented
А это спасет от этой ошибки? -

> `{"ok":false,"error_code":502,"description":"Bad Gateway"} `
> Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'result' is required for type with serial name 'Response', but it was missing at path: $
>         at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
>         at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
>         at TelegramBotService.getUpdates(TelegramBotService.kt:136)
>         at TelegramKt.main(Telegram.kt:61)
> Caused by: kotlinx.serialization.MissingFieldException: Field 'result' is required for type with serial name 'Response', but it was missing

 Или её проще фиксить дав полю `result` значение по умолчанию `null` и делать проверку в коде на `null`?

2024-06-11 10:58 UTC, danelyan requested changes

2024-06-11 10:58 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
>          val response: HttpResponse<String> = client.send(request, HttpResponse.BodyHandlers.ofString())
тут тоже нужно трайть/кетчить

2024-06-12 12:54 UTC, danelyan requested changes

2024-06-12 12:54 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    println(text)
Давай сделаем более похожим на логи или удалим вообщем.
Иначе будут засорятся файлы логов.
Например: `"handleUpdate(): chatId = $chatId, text = $text"`

2024-06-12 12:54 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +            onSuccess = { response -> response.body() },
Очень сложно получилось.
Тебе по сути нужно обозначить, что запрос не удался или были какие-то проблемы.
Не стоит делать "фейковые" данные.
```Kotlin
return responseResult.getOrNull()?.body()
```
Ну и везде где нужно, при null ничего не делать

2024-06-13 05:09 UTC, danelyan approved these changes
![yougotthis-martini](https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/3339b61b-9b81-484f-989b-a6e73733be08)

Поздравляю! Ты сделал бота на Kotlin.

Основная часть работы пройдена. Теперь этот бот твой - можешь развивать его как хочешь. Дальше я подготовил тебе развилку из 6 простеньких доработок, все они уже в боте. Однако можешь не ограничиваться только ими, любые идеи приветствуются, просто опиши в личку и мы продумаем детали.

Дальше как обычно - создаешь Pull Request (даже если что-то еще не работает - шлешь), а я пишу что можно улучшить.

2024-06-15 07:32 UTC, merged